services:
  front:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-service
    ports:
      - "8501:8501"
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile  # Path to the Dockerfile for the server service
    container_name: server-service
    volumes:
      - /weights:/weights
    ports:
      - "80:80"
    networks:
      - app-network

# Optional: Define any shared networks or volumes if needed
networks:
  app-network:
    driver: bridge