services:
  front:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-service
    ports:
      - "8501:8501"
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server-service
    volumes:
      - ./weights:/workspace/weights
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

